// Generated by https://quicktype.io
export interface ICalendarData {
  meetings: IMeeting[];
  deviations: IMeeting[];
}

export interface ISeries {
  id: string;
  frequency?: number;
  lastDate?: Date;
}
export interface IMeeting {
  id: string;
  devFrom?: string;
  series?: ISeries;
  from?: Date;
  to?: Date;
  name?: string;
  attendees?: string[];
}
